// Note you should disable Javascript Caching during Development!
// http://docs.moodle.org/dev/Developer_Mode

// http://stackoverflow.com/questions/2419749/get-selected-elements-outer-html
(function($) {
	$.fn.outerHTML = function() {
		return $(this).clone().wrap('<div></div>').parent().html();
	}
})(jQuery);

var click_on_addanswer = function() {
	/*var template = '\
		<div id="fgroup_id_answergrp${num_question}" class="fitem fitem_fgroup">\
		    <div class="fitemtitle"><div class="fgrouplabel"><label>Antwort ${num_question}</label></div></div>\
		    <fieldset class="felement fgroup">\
		        <label class="accesshide" for="id_answer_${num_question}_${num_answer}">&nbsp;</label>\
		        <input name="answer_${num_question}_${num_answer}" value="saf" id="id_answer_${num_question}_${num_answer}" type="text">\
		    </fieldset>\
		</div><div id="fitem_id_correct_${num_question}_${num_answer}" class="fitem fitem_fradio">\
		    <div class="fitemtitle"><label for="id_correct_${num_question}_${num_answer}"></label></div>\
		    <div class="felement fradio"><span><input name="correct_${num_question}" value="${num_answer}" checked="checked" id="id_correct_${num_question}_${num_answer}" type="radio"><label for="id_correct_${num_question}_${num_answer}"> ist korrekt</label></span></div>\
		</div>';*/
	var num_subquestion = this.name.substring("addanswerbtn_".length),
		$answerblock = $('div[id="fgroup_id_answergrp'+num_subquestion+'"]:first'), // selector$: "ends with"
		$correctblock = $('div[id^="fitem_id_correct_'+num_subquestion+'"]'), // selector^: "starts with"
		num_blocks = $('div[id="fgroup_id_answergrp'+num_subquestion+'"]').length,
		x = $answerblock.outerHTML() + $correctblock.outerHTML();
	//regex = new RegExp('/'+num_subquestion+'_[0-9]+'); // needed to mix regex and string
	x = x.replace(/1\W*<\/label/, (num_blocks+1)+' </label');
	x = x.replace(/[0-9]+_[0-9]+"/g, num_subquestion+'_'+(num_blocks+1)+'"');
	//var $lastcorrectblock = $('div[id="fitem_id_correct_'+num_subquestion+'_'+num_blocks+'"]'); // bad HTML generated by Moodle...
	var $lastcorrectblock = $('div[id^="fitem_id_correct_'+num_subquestion+'"]:last');
	$lastcorrectblock.html($lastcorrectblock.html() + x); // append our html
	console.log(num_blocks);
	console.log(x);
	console.log($lastcorrectblock);
	return false;
}

$(document).ready(function() {
	$('input[name^="addanswerbtn_"]').click(click_on_addanswer);
});
